language: ruby
rvm:
- 2.6.1
before_script:
- cp config/database.yml.travis config/database.yml
- psql -c 'create database travis_ci_test;' -U postgres
- curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
- chmod +x ./cc-test-reporter
- "./cc-test-reporter before-build"
script:
- bundle install --jobs=3 --retry=3
- bundle exec rake db:create
- bundle exec rake db:migrate
- bundle exec rspec
- bundle exec rubocop
after_script:
- "./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT"
notifications:
- false
env:
  global:
  - CC_TEST_REPORTER_ID=42f5ca5f88c526ac3b9464d949e97f630fc605b5eb23262a3c6f5f23b35f2b67
deploy:
  provider: heroku
  api_key:
    secure: glByR4wXsozQMi7gdcaeSqJTYqgBuO9SIXrz/mmiYFQf3NYNuTm2zVa5yWsGk1qsliqpnk9iVTN6ZXlU6vR9vR4mniEE77nIpDAfHByEGAvdcu3mp0s47RMtF5HFZc1LtKpSLJ+lFziylw0Ov2vT4Uj1AnaF1GlqcMn5iNc2m+J1FU/gW/4QZSL0ypxKJNizZDzpv3jRmi4VUQ4uvUEwt2ilDqhaIIIx7lC6Y75Cef+liWPFlvaxArUcs7QkjoJ23EteW22nMCXXBAY7B94a90l6tlHIXD899BA1Aswfw7xzCQk4RDWlVTJcCeOo00ACiGARlW1zZaBfSS5vUP44cWGoAdRJR4maBVd9QGpPTjfAAFdfRf3HQ/+gzV7Rt6Fswp1lx2SkCtrhqCz4gYdQBEW5rnJdHWVxGbnq4w9aYqlADW0t4F7JAe+jGjIjX2QOAGeFFa4AWZC5n5Mdvu0h7KJmeXByZeDubLgDPvAybg7Apo4pPrz9WAG5xGAiEErUCmtlJsnDxGFqk1S8+Ff6r8y8oNnzcmC8xCLKuv1qUQ4kOPNX+aK9GispVVqAe57GccAhdd2M7DSIalQ84rJ6nhFiEQoOkxGfAIL0jEC1X/2bXMbsrOabOL6nZKTjNLvIc/yy80xqRwQeTkixhqK3oygo2Iw3Qk5ZAnvelv8GLaI=
  app: serene-journey-16504
  on:
    repo: kindcarrier/KindCarrierBackend
dd:
  secure: dNJu6pCDjnbBAD5z8W6YRvfCbt/uml5yRN66cmZnIQZ3IsLR2mVPRD7n/y3wJu6m3hG7rQtCVdHIJaQnskl3Fxrt6KcCphgW3LQl/r8h1aaomkU/ojz238/qwxphkoFN5lfdWWNmnBEfpX6LId5PcOxBINtTYYGfj9WvESKe0WfBrSAtBKNQNbxV4nuOXedGf0TsBMOuOXOCDBii54Bm6h+pXy9RKGx8A0ENdRm84P8XELavKXxcqrecm/6mgNX5XeaavkSxkujDX9XU1jbbrl9aWW8kcqqeg4QKwd7oz1RU+2FWI5ec4McLU+cEvUJx7hSrpm2/MNnmaJYdklq2uF10xlIpe8Tkv98hRE9illQzpRoPX03cslGVS0J3zE+HFeXgUJy6ACdu/krjBQmS6ts1ahI9UWmsIqBud7ZstpfE5/A4LnaEgz5fCDtui/uad9oTw9BtsHgi6FClLYDchvbNaW6ckfg7KrjLf7wG2u9ceWCP62AUq7CKlxHgYcoecGtDvg0EBbrefLz2uhlp3gAgPhsTQ6ztrHyYvVrse5quHuYmNR4xLQXwujXkvJVYujcXL8Aai/qzsCY8/TGMjyhZYTCzF33wXSP23pMc2VGS4cfCAjm6gBbAWEvxAwgoIglfFtisPDRH9iKTNJVbf58X4bP6H4Od+4OhrifiG/0=
