module Api
  INTERNAL_SERVER_ERROR = 'INTERNAL_ERROR'.freeze
  UNAUTHORIZED_ERROR = 'UNAUTHORIZED_ERROR'.freeze
  VALIDATION_ERROR = 'VALIDATION_ERROR'.freeze
  RESOURCE_NOT_FOUND = 'RESOURCE_NOT_FOUND'.freeze
end
